name: build-npv12
env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: '1'
on:
  push:
    branches:
    - main
permissions:
  contents: read
jobs:
  build_mac:
    if: github.repository_owner == 'npv12'
    runs-on: macos-latest
    steps:
    - name: checkout_repo
      uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd
      with:
        clean: false
    - name: setup_rust
      uses: dtolnay/rust-toolchain@stable
    - name: setup_node
      uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e
      with:
        node-version: '24'
        check-latest: true
    - name: install_cmake
      run: brew install cmake
    - name: clear_target_dir_if_large
      run: ./script/clear-target-dir-if-larger-than 10 5
    - name: cargo_build_zed_and_cli
      run: cargo build --release --package zed --package cli
    - name: cargo_build_remote_server
      run: cargo build --release --package remote_server
    - name: cargo_nextest
      run: |
        cargo install cargo-nextest --locked
        cargo nextest run --workspace --no-fail-fast --no-tests=warn
      timeout-minutes: 60
      continue-on-error: true
